#项目服务器配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/db_common?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: 123456
  redis:
    host: 127.0.0.1
    password:
    port: 6379